server.port=8080
customerdata.baseurl=http://localhost:8081/api/customers
spring.main.allow-bean-definition-overriding=true
spring.ai.google.genai.api-key=AIzaSyAuGIbFhgcHfSXL2fcM18tNn9xsgrU-RME
spring.ai.google.genai.chat.options.model=gemini-2.0-flash
spring.ai.google.genai.chat.options.temperature=0.5
