server.port=8080
customerdata.baseurl=http://localhost:8081/api/customers
spring.main.allow-bean-definition-overriding=true
spring.ai.google.genai.api-key=AIzaSyC3yJyiSGio9EWaQ6ZT4jbqKF-iUcJjEXY
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.2
